[package]
name = "@EastAgile/test_move_package"
version = "1.0"

[dependencies]
AptosFramework = { git = "https://github.com/ptts1/aptos-core/blob/071ad02d3b5525a0f364e2bba0847f6f8cf3cdb9/aptos-move/framework/aptos-framework", rev = "071ad02d3b5525a0f364e2bba0847f6f8cf3cdb9" }
