[package]
name = "test_move_package"
version = "2.0.6"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
subdir = "language/move-stdlib"
rev = "main"
addr_subst = { std = "0x1" }

[addresses]
AAA = "0x0"
