[package]
name = "test_move_package"
version = "2.0.7"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
subdir = "language/move-stdlib"
rev = "583380718dc492cae1bd1f5f26b74e2f592ed60b"
addr_subst = { std = "0x1" }

[addresses]
AAA = "0x0"
